### ISSUE TITLE
Error Code 415 on any route

### ISSUE THREAD

**Issue by mblackritter** [Thomas-X/jsonapi-mock#3]
Hi @Thomas-X,

I'd the same motivation as you, after seeing JSON-Sever not being able to serve, well, JSON-API and no intentions to do so, because seemingly the concept of JSON-Api isn't even understood "there", if I read some threads there already from 2015, comparing JSON-API to Swagger... 🙄

So, congrats for the effort, and normally I just "mock" my APIs with a real implementation via Laravel and some JSON-API packages, which seems to simple, that mocking isn't really needed, which might be one of the reasons for the lack of JSON-API mocking solutions. But for a current project, it would be beneficial to have some mocking in an easy to modify and run node package, so here I'm. 🤗😹

Should this currently being in a working state? I think I setup everything so far with the sample db.json and .jsonapimockrc (E.g. "contentType": "application/json"), but on any route I get the following error response.

`{"errors":[{"code":415,"title":"Unsupported media type, your media type is: , it should be application/json","detail":"Error: Unsupported media type, your media type is: , it should be application/json\n    at /Users/black/.config/yarn/global/node_modules/jsonapi-mock/app.js:72:27\n    at Layer.handle [as handle_request] (/Users/black/.config/yarn/global/node_modules/express/lib/router/layer.js:95:5)\n`

**Comment by Thomas-X** [comment]
It should be in a working state, can you check your headers that you're sending in the request and post them here? The request needs a `Accept`: `application/vnd.api+json` header and a `Content-Type`:`application/vnd.api+json` header, if not configured otherwise. 

That's what's triggering this error, you're media type is invalid, either you're missing the accept or contentType header or I messed up 😰

**Comment by mblackritter** [comment]
Hi again @Thomas-X, you're of course absolutely right, the common mistake hit me, to just want to curl or throw everything in the browser for a quick test... 🙃

Btw., did you check out [jsonapi-server](https://github.com/holidayextras/jsonapi-server)? I think with a little fine-tuning for ease of use and lowdb support, this could be an alternative base for jsonapi-mock. If you check the [Example](https://github.com/holidayextras/jsonapi-server/tree/master/example), the data there is just static and including faker was straight forward.

Advantage of jsonapi-server would be that it already supports everything, incl. [polymorphic relationships](https://github.com/holidayextras/jsonapi-server/blob/master/example/resources/tuples.js), Swagger.json generation and even GraphQL, plus  it could make use of real DBs if wanted.
